// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvuGRAMN-R9NbvoioamTgrxp9ERqXIZzY',
    appId: '1:115365272457:web:b31a29e7fa9a1d36d95f58',
    messagingSenderId: '115365272457',
    projectId: 'taxi-app-b17d2',
    authDomain: 'taxi-app-b17d2.firebaseapp.com',
    databaseURL: 'https://taxi-app-b17d2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taxi-app-b17d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6MJGZiIknnbuId59exYzx5ptvyCC3EvI',
    appId: '1:115365272457:android:9690f8669ce79a1dd95f58',
    messagingSenderId: '115365272457',
    projectId: 'taxi-app-b17d2',
    databaseURL: 'https://taxi-app-b17d2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taxi-app-b17d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN8OEvTlKLn5ny4u7zKKXXd85JdvVw5qs',
    appId: '1:115365272457:ios:ab5cc1055dd9f29ed95f58',
    messagingSenderId: '115365272457',
    projectId: 'taxi-app-b17d2',
    databaseURL: 'https://taxi-app-b17d2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taxi-app-b17d2.appspot.com',
    androidClientId: '115365272457-iri5856qdna9rfkr0o79ukoesqbv4dqq.apps.googleusercontent.com',
    iosClientId: '115365272457-sfis9a53tnfkvaj6jjq8t3v9ikhta9qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.halago.halago',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN8OEvTlKLn5ny4u7zKKXXd85JdvVw5qs',
    appId: '1:115365272457:ios:ab5cc1055dd9f29ed95f58',
    messagingSenderId: '115365272457',
    projectId: 'taxi-app-b17d2',
    databaseURL: 'https://taxi-app-b17d2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taxi-app-b17d2.appspot.com',
    androidClientId: '115365272457-iri5856qdna9rfkr0o79ukoesqbv4dqq.apps.googleusercontent.com',
    iosClientId: '115365272457-sfis9a53tnfkvaj6jjq8t3v9ikhta9qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.halago.halago',
  );
}
